export default [
    {
        title: "Chikushōdō",
        qualification: "Royaume Sauvage",
        description: "Chikushōdō est le miroir végétal et animal de Ningendō. Créé et protégé par Mokushin, c’est un royaume où la nature est reine. La végétation y est incroyablement luxuriante et variée, les montagnes sont majestueuses et les océans immenses. En addition de l’entière faune de Ningendō, Chikushōdō est le domaine exclusif des Animaux Mythiques, des esprits changeformes Hengeyokaï ainsi que d’une myriade d’espèces inconnues. Chaque clan d’Animaux Mythiques possède un territoire et différentes habitations, villages et parfois villes, souvent inspirés par leur habitat naturel. Il n’est pas rare que deux clans se fassent la guerre et que des membres décident de s’exiler sur Ningendō tant que les affrontements font rage.\n" +
            "Chikushōdō est le royaume parallèle le plus utilisé et le plus connu des shinobis, de nombreux clans d'Animaux Mythiques ont des alliances ou des allégeances avec les villages cachés, soit avec des clans ou de simples individus.\n" +
            "**Passages :** Le nombre de lieux permettant la traversée de Chikushōdō à Ningendō est très important malgré les difficultés et dangers qui leur sont liés. La Montagne de Myobokuzan au Pays du Feu, cependant pour la trouver il faut la bénédiction d'un esprit de Chikushōdō et emprunter un sentier dont la traversée dure un mois. La Forêt aux Milles Esprits, située au sud du Pays de l'Herbe, est un passage réputé vers Chikushōdō dont l’entrée est protégée par une créature vieille de milliers d’années. La cité onirique de Kazàn, située au Pays du Vent, possède une entrée sans danger cependant sa position change constamment avec les tempêtes de sable. Les Caves de Ryūchi au Pays des Rizières offrent elles aussi une entrée vers Chikushōdō mais le labyrinthe gigantesque de ces grottes a tué bien des voyageurs. Il existe de même un énorme tourbillon dans les mers au nord du Pays de l’Eau dont le fond est censé mener directement dans les eaux de Chikushōdō, mais cela n’a jamais été prouvé.",
    },
    {
        title: "Gedō",
        qualification: "Royaume des Morts Affamés",
        description: "Ce Royaumes est l'antre des Gakis, Mort sans Repos dont la faim ne s'éteint jamais. Ils vivent sous des formes très différentes, parfois inoffensives, parfois extrêmement dangereuses. Les terres de Gedō forment un paysage dévasté sans aucun relief et sa seule lumière provient d’un soleil rouge mettant une éternité à faire ses circonvolutions. Gedō est l’un des Royaumes Parallèles les moins utilisés par le monde shinobi qui apprit très vite à se méfier de ses créatures et de leurs étranges capacités, sans pour autant perdre l’espoir d’un jour contrôler ces forces que rien ne semble pouvoir arrêter.\n" +
            "**Passages :** Nombreux sont les Maho-tsukai possédant le savoir rituel permettant d’ouvrir un portail vers Gedō tant qu’ils peuvent fournir assez de sacrifices, mais peu prennent le risque de le faire."
    },
    {
        title: "Jigokudō",
        qualification: "Royaume Maléfique",
        description: "Le sens commun a pris le nom de Jigokudō comme référence aux Royaumes Parallèles, sûrement dû au fait que les habitants de Jigokudō entretiennent des intrusions fréquentes et conséquentes vers Ningendō. Ce Royaume est la terre de la corruption, le monde des Onis, les Grands Démons ainsi que le domaine de Yama, le terrible Roi Démon, l’une des créatures les plus puissantes après les Kamis et les Mikokamis aussi appelé le Juge des Mondes. Tout ce qui existe en Jigokudō est perverti, souillé et mauvais. On y trouve les Kansen, esprits aux illusions meurtrières ainsi qu'un nombre sans fin de sombres créatures aux intentions variées ne répondant à personne sauf à elles-mêmes, s'échappant vers Ningendō pour des raisons à chaque fois différentes. Les frontières entre Jigokudō et Ningendō sont, aux dires des experts, bien trop fines et certaines terres ont été ravagées par des campagnes d’invasions démoniaques au travers des âges. Plusieurs clans ont juré d’anéantir toutes créatures de Jigokudō s’ils devaient en croiser et se sont donc dévolus à ce combat, à l’image de la coalition du Héron Argenté. Malgré les diverses animosités entre les villages cachés, ces clans n’ont eu de cesse de s’entraider et de partager leur connaissance ou leur information sur le sujet, tout en organisant un front commun lorsque les hordes de Jigokudō se répandent sur Ningendō.\n" +
            "**Passages :** Au fin fond de la Vallée Noire située au Pays des Cendres, la grotte de Toshigoku mène directement à Jigokudō mais seul un fou s’y aventurait. Elle est de même gardée par un clan de guerriers endurci par des siècles de combat. La ville-citadelle d’Onizawa située au cœur des Terres Ravagées possède un passage permanent vers Jigokudō, information que certains groupes ninjas ne cessent de diffuser afin d’initier une campagne militaire sur ces terres."
    },
    {
        title: "Meidō",
        qualification: "Royaume des Esprits Tourmentés",
        description: "Meidō accueille les âmes de tous les êtres dont la vie se termine dans la violence ou par des actes non résolus. Les esprits résidant dans ce royaume vivent dans l’attente, la confusion et le désespoir. Il n’est pas rare de les voir sous la forme de fantômes dans le monde mortel, essayant de résoudre leur vie passée en interagissant avec leurs descendants ou les individus concernés par leur mort. Normalement sans danger, leur présence peut parfois inspirer des comportements violents et être la source de grands malheurs. Lorsque les tourments d’un habitant de Meidō prennent fin, il peut enfin se réincarner et quitter ce Royaume jusqu’à sa prochaine mort s’il est de nouveau la proie d’une histoire non résolue.\n" +
            "**Passages :** Il n’existe pas de passage connu plus rapide que la mort pour rejoindre Meidō, cependant il existe une vieille cité enfouie au Pays de Ràn censée posséder un anneau gigantesque permettant de faire la traversée. Cette légende n’a jamais été confirmée et ceux revenus de Meidō furent tous atteint de folie."
    },
    {
        title: "Ningendō",
        qualification: "Royaume Mortel",
        description: "Le plan de Ningendō est le monde connu, celui que les personnages perçoivent, le monde des humains. Cet univers est vu par les autres royaumes comme un endroit éphémère et fortement fermé. Ningendō fait partie des royaumes les plus imperméables, dû aux êtres humains, mais aussi dû au fait que de nombreux kamis ainsi que de nombreux animaux mythiques et démons furent enfermés dans cette réalité à sa création.\n" +
            "Ningendō est le seul Royaume à héberger des hommes et les rares présences humaines dans les autres Royaumes sont en grande partie directement issues de Ningendō. L’espèce humaine est souvent rejetée ou combattue lorsqu’elle se trouve dans un plan qui n’est pas le sien par les habitants du plan traversé et un nombre impressionnant d’espèces cultivent une haine farouche des hommes. Certains Mushishis expliquent cette animosité d’une façon intéressante en avançant l’idée que les humains portent en eux le bouillonnement créatif et chaotique de Ningendō ainsi que la protection d’Onnotangu et d’Amaterasu, les rendant impénétrable aux yeux des autres plans. Leurs habitants se sentiraient alors menacés ou intimidés, souvent incapable de communiquer ou de comprendre l’existence même des hommes.\n" +
            "Certaines créatures comme les Renards, les Tanukis ou les Onis peuvent traverser Ningendō sans aucune difficulté."
    },
    {
        title: "Shuradō",
        qualification: "Royaume Mécanique",
        description: "Shuradō est le royaume de la vie mécanique sous toutes ses formes. Il n’existe ici rien de végétal ou animal mais le visiteur serait fou de croire qu’aucune créature douée de conscience ne foule le sol de ce plan. Créé par le Mikokami Neshin comme son domaine réservé et lieu de ses expérimentations, Shuradō est rempli d’une multitude d’êtres tous plus bizarroïdes les uns que les autres. Ses villes s’étendent à perte de vue et forment un dédale infini de rues et de centres de construction. Il est dit que le village caché d’Ame du Pays de la Pluie fut construit à la manière des villes de Shuradō et qu’il s’y trouve encore un point de passage permettant l’entrée dans le plan du Royaume Mécanique. Peut se prévalent d’avoir eu accès à ce plan et encore moins d’en être revenu sain et sauf.\n" +
            "**Passages :** Aucun passage officiel hormis la cité perdue de Rōran située au Pays du Vent n’est connu pour entrer dans ce royaume."
    },
    {
        title: "Tendō",
        qualification: "Royaume Céleste",
        description: "Tendō est le royaume de tous les Kamis, dieux mineurs et esprits sacrés. Il est chanté pour sa majesté et sa beauté sans limite. Même si les mortels ne sont que rarement acceptés à en fouler le sol, il n’est pourtant pas impossible de rendre visite aux dieux si l’on fait abstraction de tous les risques liés à la traversée. Les Kamis, Mikokamis ainsi que la Reine Soleil Amaterasu résident tous dans la ville céleste de Meiàn. Lieu sacré par excellence, Meiàn est selon les théologiens le point de force de l’univers, autour duquel tourne sans fin la spirale des mondes.\n" +
            "**Passages :** Tous les Saints Oracles, Moines, Prêtres et Illuminés entretiennent un lien étroit avec le Kami qu’ils servent. Ils peuvent ainsi ouvrir sans effort un passage vers Tendō s’ils en ont la force, mais il faudra l’ascendant du Kami pour que le passage s’ouvre et soit sans danger. Il n’est pas nécessaire de dire que cet honneur n’est pas réservé au commun des mortels, même si quelques exemples de héros purent poser leurs pieds sur le sol sacré du Royaume Céleste."
    },
    {
        title: "Todō",
        qualification: "Royaume Purifié",
        description: "Todō est le royaume des âmes ayant atteint la plénitude. C’est un royaume proche de Tendō où les âmes sages et glorieuses se retrouvent après avoir fini leur cycle de réincarnation. Il est fréquent que dans chaque famille au moins un des ancêtres ait atteint le royaume de Todō et soit révéré comme un exemple, souvent appelé par des prières afin d’aider à traverser des moments difficiles. Dans chaque maison il n’est pas rare de trouver des petits autels dédiés à tel ou tel ancêtre, accompagné d'encens et d'offrandes diverses. \n" +
            "Les habitants de Todō interagissent parfois avec leurs descendants, notamment quand ils sont en grand danger. Ils inspirent les moines dans leurs méditations et les poètes lorsqu’ils cherchent l’inspiration. Ce sont des entités très bénévolentes et apercevoir l’une d’entre elles est un signe de chance et de bonne augure.\n" +
            "Le monde ninja n’utilise quasiment jamais le royaume de Todō dans ses techniques ou ses invocations. Il est presque impossible de passer un contrat avec une de ses âmes et, hormis dans des situations de justice importante, ne parle jamais aux individus ne faisant pas partie de leur ancienne famille.\n" +
            "**Passages :** Il n’existe aucun passage connu pour rejoindre Todō."
    },
    {
        title: "Yumedō",
        qualification: "Royaume Onirique",
        description: "Yumedō est le seul royaume que le commun des mortels perçoit. En dormant l’esprit humain se déplace dans ce monde, croisant des Shiyokais créateurs de cauchemars, les mystérieux Bakus mangeurs de rêves et les Nagas, messagers oniriques. De nombreuses spéculations parlent de la nature même de Yumedō, avançant que toute chose ayant existé continue de résider dans ce Royaume et qu’il serait possible de retrouver des civilisations anciennes ainsi que des objets mythiques sur ces terres perdues. Nombre de shamans et de shujengas passent leur vie à arpenter Yumedō dans l’espoir de telles découvertes.\n" +
            "Même si Yumedō est considéré par beaucoup comme l’un des Royaumes Parallèles majeurs, il n’est pourtant pas présent dans la liste des Six Grands Royaumes du monde ninja que le Sage des Six Royaumes enseigna aux clans ancestraux et qu’il était censé pouvoir traverser à volonté.\n" +
            "**Passages :** Partout. La seule manière de pénétrer Yumedō est le rêve. Cependant sa traversée nécessite des années d’étude et de pratique pour y être libre et ne pas subir les assauts de ses créatures."
    }
];