name: Discord bot deployment
on:
    push:
        branches:
            - master
        paths:
            - "bot/**"
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '20'

            -   name: "Setup pnpm"
                uses: pnpm/action-setup@v4
                with:
                    version: 8

            -   name: Install dependencies
                run: cd ./bot && pnpm install --shamefully-hoist

            -   name: Build
                run: cd ./bot && pnpm run build && cd ../common && pnpm run build && cp ./package.json ./dist

            -   name: Stop bot process on VPS
                uses: appleboy/ssh-action@master
                with:
                    host: 45.147.97.184
                    username: discord
                    key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

                    script: |
                        export NVM_DIR=~/.nvm
                        source ~/.nvm/nvm.sh
                        pm2 stop DiscordBot
                continue-on-error: true

            -   name: Remove old build files on VPS
                uses: appleboy/ssh-action@master
                with:
                    host: 45.147.97.184
                    username: discord
                    key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

                    script: |
                        cd /home/discord
                        rm -rf bot
                        mkdir bot
                        rm -rf common
                        mkdir common
                        mkdir common/src

            -   name: Transfer build files to VPS
                run: |
                    echo "${{ secrets.BOT_SSH_PRIVATE_KEY }}" > ./bot.key
                    chmod 600 ./bot.key
                    rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./bot.key" -r ./bot/dist/ discord@45.147.97.184:/home/discord/bot
                    rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./bot.key" -r ./common/dist/ discord@45.147.97.184:/home/discord/common/src
                    rm ./bot.key

            -   name: Restart bot on VPS
                uses: appleboy/ssh-action@master
                with:
                    host: 45.147.97.184
                    username: discord
                    key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

                    script: |
                        export NVM_DIR=~/.nvm
                        source ~/.nvm/nvm.sh
                        cd /home/discord/bot
                        npm install
                        export NODE_ENV=prod
                        export DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"
                        export DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}"
                        export JWT_SECRET="${{ secrets.JWT_SECRET }}"
                        pm2 start --name=DiscordBot main.js --update-env